# generated by list_extraction_jobs.py -- do not edit by hand;
# re-run the generator if cohort.* changes in the config.
EXTRA_FLAGS="--fs-raw 10000 --base 0 --grid-width 10 --n-subsets 9 --electrodes-per-subset 1 --mfr-threshold 0.1 --w-size 0.01 --gaussian-window 0.02 --ptrain-format sparse_peaks --ptrain-varname peak_train --ptrain-name-pattern ^ptrain_\d+_DIV\d+_\w+_nbasal_\d{4}_(\d{3})\.mat$"
