# generated by list_extraction_jobs.py -- do not edit by hand;
# re-run the generator if cohort.* changes in the config.
EXTRA_FLAGS="--fs-raw 10110.09 --base 1 --grid-width 48 --n-subsets 9 --electrodes-per-subset 9 --mfr-threshold 0.1 --w-size 0.01 --gaussian-window 0.02"
